language: ruby
rvm: 2.5
cache: bundler

services:
  - redis-server

env:
  global:
    - CC_TEST_REPORTER_ID=977de4bff0d040058d177d41958c0be85960b8c9150b101a95234ee484b86ec2

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
